# *Numpy*

#### *Numpy(Numerical Python의 준말)*
##### *다차원 배열 지원*
##### *vector 개념 지원*

#### 

### 👉🏻 *array 배열 생성*

In [1]:
import numpy as np

In [10]:
x = np.array([1, 2, 3], dtype='f')

print("1차원 array")
print("x.dtype : ", x.dtype)
print("x.shape : ", x.shape)
print("x : ", x)
print("차원 수 : ", x.ndim)

1차원 array
x.dtype :  float32
x.shape :  (3,)
x :  [1. 2. 3.]
차원 수 :  1


In [13]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("2차원 array")
print("x.dtype : ", x.dtype)
print("x.shape : ", x.shape)
print("x : ", x)
print("차원 수 : ", x.ndim)

2차원 array
x.dtype :  int64
x.shape :  (2, 4)
x :  [[1 2 3 4]
 [5 6 7 8]]
차원 수 :  2


### 👉🏻 *shape 변경*

In [15]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

x.shape=(4,2)
print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 👉🏻 *arange 배열 생성*

In [20]:
# 10~20까지 2step 만큼 array
x = np.arange(10, 20, 2)
print(x)

# 0~10까지 1step 만큼 array
x = np.arange(10)
print(x)
x = x[2:7:2]
print(x)

[10 12 14 16 18]
[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


### 👉🏻 *인덱싱, 슬라이싱*

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a, a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [22]:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [27]:
# 인덱싱
a[1, 2]

6

### 👉🏻 *비교 연산자 인덱싱*

In [29]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [32]:
# 비교 연산자로 배열 값들과 비교 후 true, false 반환
print(x>5)

# 연산의 true에 해당하는 값만 추출
print(x[x>5])

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]


### 👉🏻 *NaN check*

In [33]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a)

[nan  1.  2. nan  3.  4.  5.]


In [37]:
print(np.isnan(a))
print(~np.isnan(a))
print(a[~np.isnan(a)])

[ True False False  True False False False]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]
